### ISSUE TITLE
Add customizable buttons

### ISSUE THREAD

**Issue by LucianoHanna** [LucianoHanna/FreeTree#1]
Add a way to customize button with a flag in data.json

Example:

```json
{
    "userPhoto": "link.to/photo.jpg",
    "userName": "John Doe",
    "links": [
        {
            "id": 0,
            "href": "https://www.link1.com/",
            "title": "Link 1",
-->       "style": "facebook-button"
        },
        {
            "id": 1,
            "href": "https://www.link2.com/",
            "title": "Link 2"
        }
    ]
}
```

**Comment by nerdyaltafofficial** [comment]
> Add a way to customize button with a flag in data.json
> 
> Example:
> 
> ```json
> {
>     "userPhoto": "link.to/photo.jpg",
>     "userName": "John Doe",
>     "links": [
>         {
>             "id": 0,
>             "href": "https://www.link1.com/",
>             "title": "Link 1",
> -->       "style": "facebook-button"
>         },
>         {
>             "id": 1,
>             "href": "https://www.link2.com/",
>             "title": "Link 2"
>         }
>     ]
> }
> ```

can i work on this?

**Comment by LucianoHanna** [comment]
Yes, thank you for your interest. Feel free to contact me if you have any
questions

**Comment by nerdyaltafofficial** [comment]
> Add a way to customize button with a flag in data.json
> 
> Example:
> 
> ```json
> {
>     "userPhoto": "link.to/photo.jpg",
>     "userName": "John Doe",
>     "links": [
>         {
>             "id": 0,
>             "href": "https://www.link1.com/",
>             "title": "Link 1",
> -->       "style": "facebook-button"
>         },
>         {
>             "id": 1,
>             "href": "https://www.link2.com/",
>             "title": "Link 2"
>         }
>     ]
> }
> ```

can you elaborate that what can actually do in this project?

**Comment by nerdyaltafofficial** [comment]
i am very beginner to open source project.

**Comment by LucianoHanna** [comment]
> > Add a way to customize button with a flag in data.json
> > Example:
> > ```json
> > {
> >     "userPhoto": "link.to/photo.jpg",
> >     "userName": "John Doe",
> >     "links": [
> >         {
> >             "id": 0,
> >             "href": "https://www.link1.com/",
> >             "title": "Link 1",
> > -->       "style": "facebook-button"
> >         },
> >         {
> >             "id": 1,
> >             "href": "https://www.link2.com/",
> >             "title": "Link 2"
> >         }
> >     ]
> > }
> > ```
> 
> can you elaborate that what can actually do in this project?

Now, this link:
```json
{
    "id": 0,
    "href": "https://www.link1.com/",
    "title": "Link 1"
}
```

generates this HTML:

```html
<div class="link">
    <a target="_blank" href="https://www.link1.com/">  Link 1 </a>
</div>
```

What I was thinking is an attribute in the link that would be an additional class to this div, for example:

This JSON:
```json
{
    "id": 0,
    "href": "https://www.link1.com/",
    "title": "Link 1",
    "style": "facebook-button"
}
```

Would generate this HTML:

```html
<div class="link facebook-button">
    <a target="_blank" href="https://www.link1.com/">  Link 1 </a>
</div>
```
