### ISSUE TITLE
Desktop Compatibility

### ISSUE THREAD

**Issue by LucianoHanna** [LucianoHanna/FreeTree#2]
First design of this project was mobile-first. 
Need some work on desktop's UI.

**Comment by Code-Aditya-14** [comment]
Can I work on this?

**Comment by LucianoHanna** [comment]
Yes. Feel free to contact me if you have any questions

**Comment by Code-Aditya-14** [comment]
Well I can't understand what I need to do in this issue. It is simply showing the as the image given below. Can you please elaborate what I need to do. @LucianoHanna 

![image](https://user-images.githubusercontent.com/76389639/136528289-fc234a3d-42f4-4d41-99bd-bf4e2e0d6967.png)

**Comment by LucianoHanna** [comment]
Hi, @Code-Aditya-14, firstly, thank you for your help!

I forgot to add some info in CONTRIBUTING.md about the CORS, if you open console, you will see an error in axios that only happens when you open file directly (file://). I don't think it would be a problem to this issue, but you will not see some things this way like the profile image, more than 1 button, etc.

When I made this simple CSS, I was testing only on mobile version (I was only concerned to make a good structure and interpret JSON), I think it's simple but acceptable on mobile (screenshot above)

![image](https://user-images.githubusercontent.com/22209724/136621103-64f84d2a-3e5a-41d1-b2ae-25cf2df8782c.png)

But this doesn't look good in desktop version

![image](https://user-images.githubusercontent.com/22209724/136621167-3b5d6282-6317-42cd-8d35-a9d8883ac66a.png)

I was thinking in a simple change in CSS, just limiting button width using [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries), probably this would look good too in tablet.

GitHub Page: https://lucianohanna.github.io/FreeTree/

If you have any suggestion/feedback about it, please let me know.
